#! /bin/sh

case "$1" in
    start)
        echo "Loading SPI modules"
        modprobe spidev
        modprobe spi-bcm2835
        ;;
    stop)
        echo "Unloading SPI modules"
        rmmod spi-bcm2835
        rmmod spidev
        ;;
    *)
        echo "Usage: $0 {start|stop}"
    exit 1
esac

exit 0